mocks:
   - real: http://localhost:1234/greetingAWS?wsdl
     name: greetingAWSMock
     port: 2345

   - real: http://localhost:4321/greetingBWS?wsdl
     name: greetingBWSMock
     port: 5432

proxies:
   - real: http://localhost:1234/greetingAWS?wsdl
     port: 9999
