mocks:
  - real: file:///home/besson/workspace/CHOReOS/rehearsal-study/wsdl_interfaces/resources/flightFinder/flightFinder.wsdl
    name: mocks/flightFinder
    port: 9002

  - real: file:///home/besson/workspace/CHOReOS/rehearsal-study/wsdl_interfaces/resources/webTrip/webTrip.wsdl
    name: webTripMock
    port: 4321

proxies:
  - real: file:///home/besson/workspace/CHOReOS/rehearsal-study/wsdl_interfaces/resources/carParkingWS/carParkingWS.wsdl
    port: 7003
  - real: file:///home/besson/workspace/CHOReOS/rehearsal-study/wsdl_interfaces/resources/flightFinder/flightFinder.wsdl
    port: 6002
