mocks:
  - real: file:///home/besson/workspace/CHOReOS/rehearsal-study/wsdl_interfaces/resources/flightFinder/flightFinder.wsdl
    name: mocks/flightFinder
    port: 9002

  - real: file:///home/besson/workspace/CHOReOS/rehearsal-study/wsdl_interfaces/resources/webTrip/webTrip.wsdl
    name: webTripMock
    port: 4321

proxies:
  - real: http://localhost:8003/services/carParkReservation?wsdl
    port: 6003
