package eu.choreos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2012-03-27T17:10:07.122-03:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://choreos.eu/", name = "FlightFinder")
@XmlSeeAlso({ObjectFactory.class})
public interface FlightFinder {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getFlightInfo", targetNamespace = "http://choreos.eu/", className = "eu.choreos.GetFlightInfo")
    @WebMethod
    @ResponseWrapper(localName = "getFlightInfoResponse", targetNamespace = "http://choreos.eu/", className = "eu.choreos.GetFlightInfoResponse")
    public eu.choreos.FlightInfo getFlightInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
