
/*
 * 
 */

package br.batcave;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2012-03-30T12:53:40.622-03:00
 * Generated source version: 2.4.0
 * 
 */


@WebServiceClient(name = "GreetingAWSService", 
                  wsdlLocation = "http://localhost:1234/greetingAWS?wsdl",
                  targetNamespace = "http://batcave.br/") 
public class GreetingAWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://batcave.br/", "GreetingAWSService");
    public final static QName GreetingAWSPort = new QName("http://batcave.br/", "GreetingAWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:1234/greetingAWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GreetingAWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:1234/greetingAWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GreetingAWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GreetingAWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GreetingAWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GreetingAWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GreetingAWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GreetingAWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GreetingAWS
     */
    @WebEndpoint(name = "GreetingAWSPort")
    public GreetingAWS getGreetingAWSPort() {
        return super.getPort(GreetingAWSPort, GreetingAWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GreetingAWS
     */
    @WebEndpoint(name = "GreetingAWSPort")
    public GreetingAWS getGreetingAWSPort(WebServiceFeature... features) {
        return super.getPort(GreetingAWSPort, GreetingAWS.class, features);
    }

}
