package br.batcave;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2012-03-30T13:01:02.575-03:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://batcave.br/", name = "GreetingBWS")
@XmlSeeAlso({ObjectFactory.class})
public interface GreetingBWS {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://batcave.br/GreetingBWS/sayhowRequest", output = "http://batcave.br/GreetingBWS/sayhowResponse")
    @RequestWrapper(localName = "sayhow", targetNamespace = "http://batcave.br/", className = "br.batcave.Sayhow")
    @WebMethod
    @ResponseWrapper(localName = "sayhowResponse", targetNamespace = "http://batcave.br/", className = "br.batcave.SayhowResponse")
    public java.lang.String sayhow(
        @WebParam(name = "input", targetNamespace = "")
        java.lang.String input
    );
}
