package br.batcave;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2012-03-30T12:53:40.445-03:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://batcave.br/", name = "GreetingAWS")
@XmlSeeAlso({ObjectFactory.class})
public interface GreetingAWS {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://batcave.br/GreetingAWS/sayHiRequest", output = "http://batcave.br/GreetingAWS/sayHiResponse")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://batcave.br/", className = "br.batcave.SayHi")
    @WebMethod
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://batcave.br/", className = "br.batcave.SayHiResponse")
    public java.lang.String sayHi(
        @WebParam(name = "input", targetNamespace = "")
        java.lang.String input
    );
}
