
/*
 * 
 */

package eu.choreos.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import eu.choreos.FlightFinder;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2012-03-27T17:10:07.481-03:00
 * Generated source version: 2.4.0
 * 
 */


@WebServiceClient(name = "FlightFinderImplService", 
                  wsdlLocation = "http://localhost:1234/flightFinder?wsdl",
                  targetNamespace = "http://impl.choreos.eu/") 
public class FlightFinderImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.choreos.eu/", "FlightFinderImplService");
    public final static QName FlightFinderImplPort = new QName("http://impl.choreos.eu/", "FlightFinderImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:1234/flightFinder?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FlightFinderImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:1234/flightFinder?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FlightFinderImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FlightFinderImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FlightFinderImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns FlightFinder
     */
    @WebEndpoint(name = "FlightFinderImplPort")
    public FlightFinder getFlightFinderImplPort() {
        return super.getPort(FlightFinderImplPort, FlightFinder.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FlightFinder
     */
    @WebEndpoint(name = "FlightFinderImplPort")
    public FlightFinder getFlightFinderImplPort(WebServiceFeature... features) {
        return super.getPort(FlightFinderImplPort, FlightFinder.class, features);
    }

}
